name: stackgan
channels:
  - defaults
dependencies:
  - python=3.7
  - pip=21.2.4
  - pip:
    - tensorflow==2.10.1
    - protobuf==3.19.6
    - numpy==1.21.6
    - matplotlib==3.5.3
    - pillow==9.2.0
    - requests==2.28.1
    - scikit-learn==1.0.2
